/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guerra.jgimagechoose.view;

/**
 *
 * @author Jaasiel
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form JGImageChoose
     */
    public View() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButton = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-abrir-carpeta-16.png"))); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        pnlButton.add(btnSeleccionar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-archivo-de-imagen-16.png"))); // NOI18N
        pnlButton.add(btnEliminar);

        add(pnlButton, java.awt.BorderLayout.PAGE_END);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-multiplicar-100.png"))); // NOI18N
        lblImage.setPreferredSize(new java.awt.Dimension(200, 200));
        add(lblImage, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnEliminar;
    protected javax.swing.JButton btnSeleccionar;
    protected javax.swing.JLabel lblImage;
    protected javax.swing.JPanel pnlButton;
    // End of variables declaration//GEN-END:variables
}
